### ISSUE TITLE
Dependency Missing

### ISSUE THREAD

**Issue by straticsryan** [Cernie/Pummeler#1]
Hey Cernie,

Just wanted to give you a headsup that this addon requires the dependency SuperMacro (https://legacy-wow.com/vanilla-addons/supermacro/) and if you could update the installation instructions to reflect that would be helpful to future users :)

**Comment by d-edgar** [comment]
At this time, as well, SuperMacro doesn't work in Classic.

**Comment by Cernie** [comment]
Thank you @straticsryan for bringing this up. This was a left over dependency issue that is no longer needed for this addon to work.

I also want to point out that none of my addons are designed for WoW Classic (1.13 and beyond) nor do I have any interest in updating them at this time.
