### ISSUE TITLE
Doesn't appear to work with Classic.

### ISSUE THREAD

**Issue by SunTzuTech1** [Cernie/Pummeler#2]
See this error when enabling the addon in Classic:

Message: Interface\AddOns\Pummeler\pummeler-1.8.2.lua:3: attempt to index global 'this' (a nil value)
Time: Sun Nov  1 10:18:04 2020
Count: 1
Stack: Interface\AddOns\Pummeler\pummeler-1.8.2.lua:3: attempt to index global 'this' (a nil value)

Locals:

**Comment by Cernie** [comment]
Thank you for the report. However, this addon is not compatible with WoW Classic, only with version 1.12.1
